locals {
  account_id           = "111111111"
  ad_path              = "ad"
  ad_ou_dn             = "OU=company,DC=example,DC=local"
  scope                = "global"
  category             = "security"
  env                  = "prod"
  region               = "us-east-1"
  path                 = "iac"
  infra_path           = "infra"
  pg_path              = "postgresql"
  mongo_path           = "mongodb"
  keycloak_path        = "keycloak"
  vault_mount_path     = "vss1"
  team                 = "dwh"
  service_name         = "airbyte"
  services_secret_path = "services"
  secret               = "secret"
  vault_url            = "http://10.100.100.100:8200"
  callback_url         = "http://localhost:8080/callback"
}